// src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
  title = 'This is a message from Angular 2. Hello world.!!';
}


<h1> Heading 1 </h1>
<h2> Heading 2 </h2>
<h3> Heading 3 </h3>
<h4> Heading 4 </h4>
<h5> Heading 5 </h5>
<h6> Heading 6 </h6>
<p> {{title}}} </p>
<span> This is sample text </span>
<br><br>
<button class="button primary">Primary Button</button>
<button class="button">Default Button</button>
<br><br>
<a href="#">Sample link</a>
<br><hr>
<br><br>
<div>
    <input id="checkBox" type="checkbox" name="sampleCheck" value="cb">
    <label for="checkBox"><span><span></span></span>Check Box</label>
</div>
<div>
    <input id="radioButton1" type="radio" name="sampleRadio" value="rb1">
    <label for="radioButton1"><span><span></span></span>Radio Button 1</label>
</div>
<div>
    <input id="radioButton2" type="radio" name="sampleRadio" value="rb2">
    <label for="radioButton2"><span><span></span></span>Radio Button 2</label>
</div>
<br>
<input type="text">
<br><br>
<textarea rows="5" cols="50">

</textarea>

// src/App.jsx
import React from 'react';
import './styles/global-style.scss';

class App extends React.Component {
   render() {
      return (
          <div>
         <h1>
            Hello World!!!
         </h1>
         <h2>
            Hello World!!!
         </h2>
         <h3>
            Hello World!!!
         </h3>
         <h4>
            Hello World!!!
         </h4>
         <h5>
            Hello World!!!
         </h5>
         <h6>
            Hello World!!!
         </h6>
         <p>
             A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
        </p>
        <button class="button primary">Test</button>
        <button class="button default">Test</button>
        <input type="checkbox"/>
        <label class="check-box-container">
            Test
            <input type="checkbox"/>
            <span class="check-box"></span>
        </label>
        <input type="radio"/>
        <label class="radio-box-container">
            Test
            <input type="radio" name="test"/>
            <span class="radio-box"></span>
        </label>
        <label class="radio-box-container">
            Test
            <input type="radio" name="test"/>
            <span class="radio-box"></span>
        </label>
        <label class="radio-box-container">
            Test
            <input type="radio" name="test"/>
            <span class="radio-box"></span>
        </label>
        </div>
      );
   }
}
export default App;
